
const DataList = ({ object }) => {
  return (
    <div>
      <div className="font-bold mb-2">This QrCode is generated by our WebApp:</div>
      <ul>
        <li>First Name: {object.firstName}</li>
        <li>Last Name: {object.lastName}</li>
        <li>Order Id: {object.orderId}</li>
      </ul>
    </div>
  );
}

export default DataList;