import React from 'react'
import { useState } from "react"
import QrReader from "react-qr-reader";
import DataList from './DataList';

function QrCamScanner() {

  const [scanResultWebCam, setScanResultWebCam] = useState('');
  const [isScanned, setIsScanned] = useState(false);

  const handleErrorWebCam = (error) => {
    console.log(error);
  }

  const isJSON = fileToTest => {
    try {
      JSON.parse(fileToTest);
    } catch(e) {
      return false;
    }
    return true;
  }

  const decrypt = data => {
    let finalData = data;
    let retrievedData;

    if (isJSON(data)) finalData = JSON.parse(data);

    retrievedData = localStorage.getItem(finalData);
  
    if (retrievedData === null) return 'This QrCode is not generated by our WebApp';
    else return <DataList object={JSON.parse(retrievedData)} />;
  }

  const handleScanWebCam = (result) => {
    if (result) {
      setScanResultWebCam(result);
      setIsScanned(true);
    }
  }

  return (
    
    <>
      <h3 className='text-gray-700 text-base font-bold mb-2'>Scan using your camera</h3>
      <QrReader
        onError={handleErrorWebCam}
        onScan={handleScanWebCam}
        style={{ width: '20rem' }}
      />
      <div></div>
      {isScanned &&
        <div className='w-full'>
          <span>output:</span><br />
          {scanResultWebCam}<br />
          {decrypt(scanResultWebCam)}
        </div>}
    </>
  )
}

export default QrCamScanner;
